### ISSUE TITLE
fish-shell not working

### ISSUE THREAD

**Issue by denji** [wilmoore/php-version#36]
[fishShell](http://fishshell.com/): https://github.com/fish-shell/fish-shell/
oh-my-fish: https://github.com/bpinto/oh-my-fish

~/.config/fish/config.fish

```
. $(brew --prefix php-version)/php-version.sh
```

```
fish: Illegal command name 'COLOR_NORMAL=$(tput sgr0)'
/usr/local/Cellar/php-version/0.10.4/php-version.sh (line 10):   COLOR_NORMAL=$(tput sgr0)
                                                                 ^
in . (source) call of file '/usr/local/Cellar/php-version/0.10.4/php-version.sh',
    called on standard input,

fish: Illegal command name 'COLOR_REVERSE=$(tput smso)'
/usr/local/Cellar/php-version/0.10.4/php-version.sh (line 11):   COLOR_REVERSE=$(tput smso)
                                                                 ^
in . (source) call of file '/usr/local/Cellar/php-version/0.10.4/php-version.sh',
    called on standard input,

fish: Illegal command name '[[ -n $(command -v brew) ]]'
/usr/local/Cellar/php-version/0.10.4/php-version.sh (line 25):   if [[ -n $(command -v brew) ]]; then
                                                                    ^
in . (source) call of file '/usr/local/Cellar/php-version/0.10.4/php-version.sh',
    called on standard input,
```

**Comment by corysimmons** [comment]
Rewrite in Go so works everywhere pls. 💯

**Comment by wilmoore** [comment]
After evaluating `go-lang` I've decided I have no long-term interest in that language. If I re-write this, it will likely be done with `rust`.

**Comment by wilmoore** [comment]
SEE: https://github.com/wilmoore/php-version/issues/56

**Comment by corysimmons** [comment]
I keep hearing people like Rust. I should probably read about it.

I ended up going with phpbrew out of impatience, but this might be a good project to play around with Rust (assuming you aren't already a master of it). :}

**Comment by wilmoore** [comment]
The more important bit of info is that I haven't done PHP work in several years and I don't plan to change that. That being said, `php-version` is a simple program and I do like solving these types of problem so I'll likely get around to it at some point.

**Comment by corysimmons** [comment]
Yeah, I feel ya. I wish I could live in ES6+ Node forever but WordPress gonna WordPress.
