### ISSUE TITLE
Support for hhvm

### ISSUE THREAD

**Issue by SimonSimCity** [wilmoore/php-version#41]
Is there any interest for adding support for HHVM here?

As it's a more and more growing alternative to the known PHP interpreter, it's may worth adding here as another way to execute PHP scripts.

**Comment by cerw** [comment]
:+1:  for this please

**Comment by wilmoore** [comment]
Yup, this is completely out of scope as mentioned by @SimonSimCity. The binary is called `hhvm` so it wouldn't make sense to overload this tool with something completely unrelated.

**Comment by SimonSimCity** [comment]
@cerw If you want, you can easily install hhvm on a machine where you have php installed and run them side-by-side. That's not as easy as installing php56 and php70 side-by-side, and I guess that this is the problem this tool here is trying to solve.

I agree with you, that hhvm is important for you as a library-developer, but it's not the spot of the scope of this project as you can run hhvm while having another php version installed.

**Comment by wilmoore** [comment]
> ... That's not as easy as installing php56 and php70 side-by-side

@SimonSimCity did you mean to say "It's not as easy to install php56 and php70 side-by-side"?

**Comment by SimonSimCity** [comment]
@wilmoore No, but I meant it's less painful running hhvm and php (in whatever version) side-by-side instead of running different php versions side-by-side where you always have to switch. Therefore you don't actually need this tool for supporting hhvm. You just have to use your commandline-tools correctly, create a symlink to php or to update your webserver.

**Comment by wilmoore** [comment]
@SimonSimCity :+1:
