### ISSUE TITLE
brew install doesn't create symlink

### ISSUE THREAD

**Issue by sminnee** [wilmoore/php-version#47]
In 0.12.0, `brew link php-version` doesn't appear to create a symlink in /usr/local/bin.

Here's the content of the Cellar

		cd /usr/local/Cellar/php-version/0.12.0/
		ls -la
		total 56
		drwxr-xr-x  7 sminnee  admin   238 27 Aug 09:27 .
		drwxr-xr-x  3 sminnee  admin   102 27 Aug 09:27 ..
		-rw-r--r--  1 sminnee  admin   310 27 Aug 09:27 INSTALL_RECEIPT.json
		-rw-r--r--  1 sminnee  wheel  1080  2 Jul  2014 LICENSE
		-rw-r--r--  1 sminnee  wheel  6568  2 Jul  2014 README.md
		-rwxr-xr-x  1 sminnee  wheel   897  2 Jul  2014 bug-report.sh
		-rwxr-xr-x  1 sminnee  wheel  5521  2 Jul  2014 php-version.sh

And the content of INSTALL_RECEIPT.json

		sminnee@Walnut /u/l/C/p/0.12.0> cat INSTALL_RECEIPT.json 
		{"used_options":[],"unused_options":[],"built_as_bottle":false,"poured_from_bottle":false,"time":1440624479,"HEAD":"08bb15a8a5e4aa76c61a7f9f2a68b598b3ee6a00","stdlib":null,"compiler":"clang","source":{"path":"/usr/local/Library/Taps/homebrew/homebrew-php/Formula/php-version.rb","tap":"homebrew/homebrew-php"}}

**Comment by sminnee** [comment]
Also, php-version.sh doesn't have an `#!` header, which means it doesn't work on Fish shell.

**Comment by sminnee** [comment]
Hrm, upon further digging I see that your config instructions cover this. Is there a reason that you haven't just made a shell-script call php-version? Your set-up makes it hard to use other shells.

**Comment by wilmoore** [comment]
Hi @sminnee - Yeah, I agree. It's kind of a pain. There are pros and cons to doing it either way, but if I were to do it again, I'd probably make it a script instead.
