### ISSUE TITLE
init script is not finding my brew-installed php versions. all installed today.

### ISSUE THREAD

**Issue by erikdstock** [wilmoore/php-version#50]
Was looking for a php version manager when i came upon this.

## System

  Darwin Eriks-MacBook-Pro.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64

## Script

  TYPE:    php-version
  VERSION: php-version v0.12.0

## Environment

  SHELL:        /bin/bash
  PATH:         /Users/eriks/.rvm/gems/ruby-2.1.4/bin:/Users/eriks/.rvm/gems/ruby-2.1.4@global/bin:/Users/eriks/.rvm/rubies/ruby-2.1.4/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/eriks/Documents/android/sdk/build-tools:/Users/eriks/Documents/android/sdk:/Users/eriks/Documents/android/sdk/platform-tools:/Users/eriks/Documents/android/sdk/tools:/Users/eriks/.rvm/bin:/Users/eriks/.rvm/bin
  PHPS:         
  PHP_VERSIONS: 

## Homebrew

  VERSION: 0.9.5 (git revision 9b85e; last commit 2015-11-23)
  PATH:    /usr/local/bin/brew
  PHPS:    /usr/local/Cellar/php56

## PHP

  VERSION: 5.6.15

## INI

  Configuration File (php.ini) Path: /usr/local/etc/php/5.6
  Loaded Configuration File:         /usr/local/etc/php/5.6/php.ini
  Scan for additional .ini files in: /usr/local/etc/php/5.6/conf.d
  Additional .ini files parsed:      (none)

**Comment by erikdstock** [comment]
```0.12.0 [master] :> php-version 5
Sorry, but php-version was unable to find version '5' under ''.
0.12.0 [master] :> php-version
0.12.0 [master] :>```

**Comment by wilmoore** [comment]
Would you mind posting the output of the following command:

```
find $(brew --cellar) -maxdepth 1 -type d | grep -E 'php[0-9]*$'
```

and

```
ls $(find $(brew --cellar) -maxdepth 1 -type d | grep -E 'php[0-9]*$')
```

**Comment by erikdstock** [comment]
php-version [master] :> find $(brew --cellar) -maxdepth 1 -type d | grep -E
'php[0-9]*$'
/usr/local/Cellar/php56
php-version [master] :> ls $(find $(brew --cellar) -maxdepth 1 -type d |
grep -E 'php[0-9]*$')
ls: /usr/local/Cellar/\033[01;31m\033[Kphp56\033[m\033[K: No such file or
directory

Looking at the above output - i think this may be an encoding issue. my
initial bug report output has the php56 in red, but after pbcopy the php56
characters come through similarly garbled.

I'm currently loading php-version at the bottom of my .bash_profile, fwiw.



-Erik

**Comment by wilmoore** [comment]
What do you get with the following command:

```
file /usr/local/Cellar/php56
```

**Comment by erikdstock** [comment]
/usr/local/Cellar/php56: directory



-Erik

**Comment by wilmoore** [comment]
Sorry for the delay (holidays)...Can you also get the output of:

```
tree -d -L 4 $(find $(brew --cellar) -maxdepth 1 -type d | grep -E 'php[0-9]*$')
```

**Comment by erikdstock** [comment]
:> tree -d -L 4 $(find $(brew --cellar) -maxdepth 1 -type d) | grep -E 'php[0-9]*$'
├── php56
│       │   └── php
│       │   └── php
│       ├── php
│       │   └── php
/usr/local/Cellar/php56
    │   └── php
    │   └── php
    ├── php
    │   └── php

**Comment by wilmoore** [comment]
That doesn't look quite right. For example, here is the output from my own system:

```
/Users/wilmoore/.homebrew/Cellar/php56
└── 5.6.9
    ├── bin
    ├── include
    │   └── php
    │       ├── TSRM
    │       ├── Zend
    │       ├── ext
    │       ├── main
    │       └── sapi
    ├── lib
    │   └── php
    │       ├── Archive
    │       ├── Console
    │       ├── OS
    │       ├── PEAR
    │       ├── Structures
    │       ├── XML
    │       ├── build
    │       ├── data
    │       ├── doc
    │       └── test
    ├── libexec
    │   └── apache2
    ├── php
    │   └── php
    │       └── fpm
    ├── sbin
    ├── share
    │   └── man
    │       ├── man1
    │       └── man8
    └── var
        └── log

33 directories
```

**Comment by erikdstock** [comment]
I had some inherited dotfiles setting causing that problem by setting my grep output to always use colors. with it fixed:
```
/usr/local/Cellar/php56
└── 5.6.16
    ├── bin
    ├── include
    │   └── php
    │       ├── TSRM
    │       ├── Zend
    │       ├── ext
    │       ├── main
    │       └── sapi
    ├── lib
    │   └── php
    │       └── build
    ├── libexec
    │   └── apache2
    ├── php
    │   └── php
    │       └── fpm
    ├── sbin
    ├── share
    │   └── man
    │       ├── man1
    │       └── man8
    └── var
        └── log
```

**Comment by wilmoore** [comment]
So, does this correct things for you or are you still having a problem?

**Comment by REBELinBLUE** [comment]
@erikdstock how did you fix this without changing your global grep alias? Would it not be an idea to use "command grep" or "\grep" that what it doesn't use the user's aliases

**Comment by erikdstock** [comment]
Yep, i resolved it using a similar approach though those should work too.
thanks!

**Comment by REBELinBLUE** [comment]
I'll see if I can do a PR although it turned out that just adding command to the grep command didn't fix my problem, it was then able to list the installed versions but when I tried switching it again said it couldn't find the version so I will need to play around more

**Comment by wilmoore** [comment]
OK @REBELinBLUE - thanks. Let me know if you figure anything out. In the meantime, looks like @erikdstock has started a PR.
