### ISSUE TITLE
Sorry, but php-version was unable to find version '5' under ''.

### ISSUE THREAD

**Issue by r34ch** [wilmoore/php-version#51]
I am using `zsh` on Ubuntu 14.04 but I think I have missed something in setting up my `.zshrc` file. I have used php-builder and have built the latest php 5 and 7 versions within `~/local/php` whilst php-version is installed in the default `~/local/php-version`

I added this line to my `.zshrc` file - `export PHP_VERSIONS="$HOME/local/php"`

Using the command `php-version` without any commands returns nothing whilst defining an exact version yields the title error.

**Comment by wilmoore** [comment]
You've got a couple options it seems:

1. Move your installed php versions to `~/.phps`
2. Put `~/local/php` into `$PHP_VERSIONS`

```
export PHP_VERSIONS="$HOME/local/php"
```

**Comment by r34ch** [comment]
@wilmoore Would you mind elaborating on point 2? I tried point 1 but I still get the same error.

Perhaps I have not built the php version correctly, but I assume the error _should_ say something like `Sorry, but php-version was unable to find version '7.0.1' under ''/path/to/php_versions".`?

**Comment by wilmoore** [comment]
Can you run the `bug-report` script?
https://github.com/wilmoore/php-version#having-issues

**Comment by r34ch** [comment]
@wilmoore 
```
bug-report.sh:6: command not found: brew
bug-report.sh:6: command not found: brew
## System

  Linux plex 3.19.0-43-generic #49~14.04.1-Ubuntu SMP Thu Dec 31 15:44:49 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

## Script

  TYPE:    php-version
  VERSION: php-version v0.12.0

## Environment

  SHELL:        /usr/bin/zsh
  PATH:         /home/dr/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
  PHPS:         
  PHP_VERSIONS: /home/dr/local/php /home/dr/php/versions

## Homebrew

  VERSION: 
  PATH:    
  PHPS:    

## PHP

  VERSION: 5.5.9-1ubuntu4.14

## INI

  Configuration File (php.ini) Path: /etc/php5/cli
  Loaded Configuration File:         /etc/php5/cli/php.ini
  Scan for additional .ini files in: /etc/php5/cli/conf.d
  Additional .ini files parsed:      /etc/php5/cli/conf.d/05-opcache.ini,
  /etc/php5/cli/conf.d/10-pdo.ini,
  /etc/php5/cli/conf.d/20-curl.ini,
  /etc/php5/cli/conf.d/20-imagick.ini,
  /etc/php5/cli/conf.d/20-json.ini,
  /etc/php5/cli/conf.d/20-mcrypt.ini,
  /etc/php5/cli/conf.d/20-mysql.ini,
  /etc/php5/cli/conf.d/20-mysqli.ini,
  /etc/php5/cli/conf.d/20-pdo_mysql.ini,
  /etc/php5/cli/conf.d/20-readline.ini
```

**Comment by wilmoore** [comment]
Would you mind providing output of `ls /home/dr/local/php`

**Comment by r34ch** [comment]
~/local/php
```
bin  etc  include  lib  libexec  php  sbin  share  var
```

Ok I have it half working now. I have a php version installed in `/local/php-version/php-version.sh` and when I include the entire line `export PHP_VERSIONS="$HOME/local/php $HOME/php/versions"` in my `.zshrc` file and source the `.zshrc` file then a version is listed.

If I remove `$HOME/local/php` from the export line, everything seems to break. Why must this directory be listed in the export path if no version of php has been built there? Am I missing something obvious?

Also if I have the php build in a sub directory i.e. `~/php/versions/five` and update the export line `$HOME/php/versions/five` and source the ~/.zshrc file, again nothing is shown. How do you point to various builds of php?

**Comment by wilmoore** [comment]
If you indeed only have versions in `$HOME/php/versions`, then your export line should be:

```
export PHP_VERSIONS="$HOME/php/versions"
```

Can you make that change then run the support script again? Would you also provide a directory listing of `$HOME/php/versions`?

> Also if I have the php build in a sub directory i.e. ~/php/versions/five and update the export line $HOME/php/versions/five and source the ~/.zshrc file, again nothing is shown. How

`php-version` expects to see one or more php versions in directories under a give prefix. So, if you have something like:

```
$HOME/php/versions/5.5.31
$HOME/php/versions/5.6.17
```

You should be able to switch between these two.

Keep in mind, with the above, you would need to set `export PHP_VERSIONS="$HOME/php/versions"`.

Thanks.

**Comment by r34ch** [comment]
Ok after naming them to the correct version numbers within `~/php/versions` (and not `~/local/php/versions`) I finally have a highlighted and stared version number listed when I use `php-version`. Strange however that when I had a version of php compiled directly within `~/local/php/` it listed the version number with `php-version` but without any highlighting or star. 

I cannot see any of this information in the README however?

**Comment by wilmoore** [comment]
Thanks @r34ch...this is great feedback. I really appreciate it. I think you are right in that the README could be a bit more specific about the layout of the versions directory. I'll try to fix that up soon.

**Comment by r34ch** [comment]
@wilmoore If I was more familiar with your project and more competent with Linux overall I would have offered a PR to save you the trouble. Anyways, all works nicely now, thanks for your continued help and for this great little tool.

One last somewhat unrelated question though; I assume this doesn't work with apache? If not, would you consider such integration in the future?

**Comment by r34ch** [comment]
@wilmoore ...guessing not?

**Comment by wilmoore** [comment]
Oops, sorry I missed your question. No, this isn't meant to work with Apache.

**Comment by r34ch** [comment]
@wilmoore thanks, good to know.

**Comment by jpswade** [comment]
I too have this issue:

`# source $HOME/local/php-version/php-version.sh && php-version 5.6
Sorry, but php-version was unable to find version '5.6' under ''.`

I couldn't see an obvious issue.
