### ISSUE TITLE
No symlink for /usr/local/bin/php

### ISSUE THREAD

**Issue by noplanman** [wilmoore/php-version#55]
I'm using brew and the different brew PHP versions.
Changing the version with brew, I would do:
```sh
brew unlink <current version> #e.g. brew unlink php56
brew link <new version>       #e.g. brew link php70
```

`php-version` only adjusts the PATH, not the actual symlinks.
Using PhpStorm, this means that each time I change the PHP version, I also have to re-set the path to the PHP binary in the settings, as I can't just point it to `/usr/local/bin/php`.

How do you solve this issue?

**Comment by wilmoore** [comment]
I don't use PhpStorm so I am not sure how much I can help; however, I checked out the documentation and I noticed this:

https://www.jetbrains.com/help/phpstorm/10.0/working-with-embedded-local-terminal.html

Seems like if you are in that environment, shell changes would be picked up automatically without issue. Anything else is going to likely tie you directly to a specific fixed path.

Seems like this could be easily resolved if PhpStorm supported reading environment variables dynamically.

I'm not sure how much this helps you, but I hope it helps nonetheless.
