### ISSUE TITLE
[Feature] Switch PHP versions when entering in a project folder

### ISSUE THREAD

**Issue by ProGM** [wilmoore/php-version#58]
Some similar tools, like phpenv/rbenv and similar projects, are automatically identifying the required php version you need for a certain project, by reading the content of a file in the project directory (for example: `.php-version`.

It would be very cool to have this feature here as well!

Example `.php-version` file:
```
7.0.15
```

I temporary implemented this by aliasing the `cd` command like this:

```bash
function cd() {
  for last; do true; done
  [ -f "$last/.php-version" ] && php-version $(cat $last/.php-version)
  builtin cd "$@"
}
```

**Comment by wilmoore** [comment]
Hi @ProGM,

I personally use `direnv` for that.
https://github.com/wilmoore/php-version/issues/57

Currently, you can add a custom function to `direnv` called `use_php`; however, at some point, I (or someone else with some free cycles) will add this to the stdlib of `direnv` so it will have this capability out of the box.

Hope this helps.
