### ISSUE TITLE
brew versions not picked up anymore

### ISSUE THREAD

**Issue by iluuu1994** [wilmoore/php-version#65]
Brew seems to have migrated PHP into the Core repository:

**https://github.com/Homebrew/homebrew-php**:

> As announced on the 19th of January this tap was archived on 31st March 2018.
>
> All formulae were migrated to Homebrew/homebrew-core or deleted by 7th April.

As a result, PHP is now called `php@7.0`, `php@7.1`, etc.

However, **php-version** matches the php versions by `php70`, `php71`, you get the drill:  
https://github.com/wilmoore/php-version/blob/master/php-version.sh#L31

Adjusting the pattern to use `php@[0-9\.]*$` fixes the problem.

This probably needs a better, more backwards compatible solution. But I'd appreciate a fix.

**Comment by MatthD** [comment]
+1

**Comment by 8090Lambert** [comment]
+1

**Comment by l1905** [comment]
will cause a new problem that it can not find any versions except php7+, example I can not find php5.6 version
so adjust the pattern to use `php[0-9\.@]*$` fixes the problem.

**Comment by wilmoore** [comment]
This has been corrected with #66.
