### ISSUE TITLE
Doesn't switch versions on ubuntu

### ISSUE THREAD

**Issue by daraul** [wilmoore/php-version#69]
I've tried everything to fix this on my own. Even cloning the repo and trying a few changes myself to no avail. I've even toyed with the idea of uninstalling php completely and reinstalling it after installing this. I'm not sure what the issue is, but I know this worked just fine in the past. 

Before setting PHP_VERSIONS in my bashrc file, I get the 'you have no php versions installed' message as expected. Once I set that, changing a version returns no output, but doesn't change the php version. I have 5.6, 7.0, 7.1 and 7.2 installed (7.2 active).

Then I installed linuxbrew-wrapper, and that didn't help. That's when I uninstalled it, gave up and came to submit this issue. Any ideas?  

bug-report.sh output:
The program 'brew' is currently not installed. You can install it by typing:
sudo apt install linuxbrew-wrapper
The program 'brew' is currently not installed. You can install it by typing:
sudo apt install linuxbrew-wrapper
## System

  Linux phoenix 4.4.0-122-generic #146-Ubuntu SMP Mon Apr 23 15:34:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## Script

  TYPE:    php-version
  VERSION: php-version v0.12.0

## Environment

  SHELL:        /bin/bash
  PATH:         /home/daraul/.nvm/versions/node/v9.8.0/bin:/home/daraul/.sdkman/candidates/gradle/current/bin:/home/daraul/bin:/home/daraul/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/daraul/.rvm/bin:/usr/local/Android/android-studio/bin:/usr/local/Android/Sdk/platform-tools:/usr/local/Android/Sdk/tools:/home/daraul/.gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b/gradle-2.2.1/bin:/home/daraul/.rvm/bin:/home/daraul/.config/composer/vendor/bin:/usr/local/Android/android-studio/bin:/usr/local/Android/Sdk/platform-tools:/usr/local/Android/Sdk/tools:/home/daraul/.gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b/gradle-2.2.1/bin:/home/daraul/.rvm/bin:/home/daraul/.config/composer/vendor/bin:/usr/local/Android/android-studio/bin:/usr/local/Android/Sdk/platform-tools:/usr/local/Android/Sdk/tools:/home/daraul/.gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b/gradle-2.2.1/bin:/home/daraul/.rvm/bin:/home/daraul/.config/composer/vendor/bin:/usr/local/Android/android-studio/bin:/usr/local/Android/Sdk/platform-tools:/usr/local/Android/Sdk/tools:/home/daraul/.gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b/gradle-2.2.1/bin:/home/daraul/.rvm/bin:/home/daraul/.config/composer/vendor/bin:/usr/local/Android/android-studio/bin:/usr/local/Android/Sdk/platform-tools:/usr/local/Android/Sdk/tools:/home/daraul/.gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b/gradle-2.2.1/bin:/home/daraul/.rvm/bin:/home/daraul/.config/composer/vendor/bin:/usr/local/Android/android-studio/bin:/usr/local/Android/Sdk/platform-tools:/usr/local/Android/Sdk/tools:/home/daraul/.gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b/gradle-2.2.1/bin:/home/daraul/.rvm/bin:/home/daraul/.config/composer/vendor/bin:/usr/local/Android/android-studio/bin:/usr/local/Android/Sdk/platform-tools:/usr/local/Android/Sdk/tools:/home/daraul/.gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b/gradle-2.2.1/bin:/home/daraul/.rvm/bin:/home/daraul/.config/composer/vendor/bin
  PHPS:         
  PHP_VERSIONS: /etc/php/

## Homebrew

  VERSION: 
  PATH:    
  PHPS:    

## PHP

  VERSION: 7.2.4-1+ubuntu16.04.1+deb.sury.org+1

## INI

  Configuration File (php.ini) Path: /etc/php/7.2/cli
  Loaded Configuration File:         /etc/php/7.2/cli/php.ini
  Scan for additional .ini files in: /etc/php/7.2/cli/conf.d
  Additional .ini files parsed:      /etc/php/7.2/cli/conf.d/10-mysqlnd.ini,
  /etc/php/7.2/cli/conf.d/10-opcache.ini,
  /etc/php/7.2/cli/conf.d/10-pdo.ini,
  /etc/php/7.2/cli/conf.d/15-xml.ini,
  /etc/php/7.2/cli/conf.d/20-calendar.ini,
  /etc/php/7.2/cli/conf.d/20-ctype.ini,
  /etc/php/7.2/cli/conf.d/20-curl.ini,
  /etc/php/7.2/cli/conf.d/20-dom.ini,
  /etc/php/7.2/cli/conf.d/20-exif.ini,
  /etc/php/7.2/cli/conf.d/20-fileinfo.ini,
  /etc/php/7.2/cli/conf.d/20-ftp.ini,
  /etc/php/7.2/cli/conf.d/20-gd.ini,
  /etc/php/7.2/cli/conf.d/20-gettext.ini,
  /etc/php/7.2/cli/conf.d/20-iconv.ini,
  /etc/php/7.2/cli/conf.d/20-json.ini,
  /etc/php/7.2/cli/conf.d/20-mbstring.ini,
  /etc/php/7.2/cli/conf.d/20-mysqli.ini,
  /etc/php/7.2/cli/conf.d/20-pdo_mysql.ini,
  /etc/php/7.2/cli/conf.d/20-phar.ini,
  /etc/php/7.2/cli/conf.d/20-posix.ini,
  /etc/php/7.2/cli/conf.d/20-readline.ini,
  /etc/php/7.2/cli/conf.d/20-shmop.ini,
  /etc/php/7.2/cli/conf.d/20-simplexml.ini,
  /etc/php/7.2/cli/conf.d/20-sockets.ini,The program 'brew' is currently not installed. You can install it by typing:
sudo apt install linuxbrew-wrapper
The program 'brew' is currently not installed. You can install it by typing:
sudo apt install linuxbrew-wrapper
## System

  Linux phoenix 4.4.0-122-generic #146-Ubuntu SMP Mon Apr 23 15:34:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## Script

  TYPE:    php-version
  VERSION: php-version v0.12.0

## Environment

  SHELL:        /bin/bash
  PATH:         /home/daraul/.nvm/versions/node/v9.8.0/bin:/home/daraul/.sdkman/candidates/gradle/current/bin:/home/daraul/bin:/home/daraul/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/daraul/.rvm/bin:/usr/local/Android/android-studio/bin:/usr/local/Android/Sdk/platform-tools:/usr/local/Android/Sdk/tools:/home/daraul/.gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b/gradle-2.2.1/bin:/home/daraul/.rvm/bin:/home/daraul/.config/composer/vendor/bin:/usr/local/Android/android-studio/bin:/usr/local/Android/Sdk/platform-tools:/usr/local/Android/Sdk/tools:/home/daraul/.gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b/gradle-2.2.1/bin:/home/daraul/.rvm/bin:/home/daraul/.config/composer/vendor/bin:/usr/local/Android/android-studio/bin:/usr/local/Android/Sdk/platform-tools:/usr/local/Android/Sdk/tools:/home/daraul/.gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b/gradle-2.2.1/bin:/home/daraul/.rvm/bin:/home/daraul/.config/composer/vendor/bin:/usr/local/Android/android-studio/bin:/usr/local/Android/Sdk/platform-tools:/usr/local/Android/Sdk/tools:/home/daraul/.gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b/gradle-2.2.1/bin:/home/daraul/.rvm/bin:/home/daraul/.config/composer/vendor/bin:/usr/local/Android/android-studio/bin:/usr/local/Android/Sdk/platform-tools:/usr/local/Android/Sdk/tools:/home/daraul/.gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b/gradle-2.2.1/bin:/home/daraul/.rvm/bin:/home/daraul/.config/composer/vendor/bin:/usr/local/Android/android-studio/bin:/usr/local/Android/Sdk/platform-tools:/usr/local/Android/Sdk/tools:/home/daraul/.gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b/gradle-2.2.1/bin:/home/daraul/.rvm/bin:/home/daraul/.config/composer/vendor/bin:/usr/local/Android/android-studio/bin:/usr/local/Android/Sdk/platform-tools:/usr/local/Android/Sdk/tools:/home/daraul/.gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b/gradle-2.2.1/bin:/home/daraul/.rvm/bin:/home/daraul/.config/composer/vendor/bin
  PHPS:         
  PHP_VERSIONS: /etc/php/

## Homebrew

  VERSION: 
  PATH:    
  PHPS:    

## PHP

  VERSION: 7.2.4-1+ubuntu16.04.1+deb.sury.org+1

## INI

  Configuration File (php.ini) Path: /etc/php/7.2/cli
  Loaded Configuration File:         /etc/php/7.2/cli/php.ini
  Scan for additional .ini files in: /etc/php/7.2/cli/conf.d
  Additional .ini files parsed:      /etc/php/7.2/cli/conf.d/10-mysqlnd.ini,
  /etc/php/7.2/cli/conf.d/10-opcache.ini,
  /etc/php/7.2/cli/conf.d/10-pdo.ini,
  /etc/php/7.2/cli/conf.d/15-xml.ini,
  /etc/php/7.2/cli/conf.d/20-calendar.ini,
  /etc/php/7.2/cli/conf.d/20-ctype.ini,
  /etc/php/7.2/cli/conf.d/20-curl.ini,
  /etc/php/7.2/cli/conf.d/20-dom.ini,
  /etc/php/7.2/cli/conf.d/20-exif.ini,
  /etc/php/7.2/cli/conf.d/20-fileinfo.ini,
  /etc/php/7.2/cli/conf.d/20-ftp.ini,
  /etc/php/7.2/cli/conf.d/20-gd.ini,
  /etc/php/7.2/cli/conf.d/20-gettext.ini,
  /etc/php/7.2/cli/conf.d/20-iconv.ini,
  /etc/php/7.2/cli/conf.d/20-json.ini,
  /etc/php/7.2/cli/conf.d/20-mbstring.ini,
  /etc/php/7.2/cli/conf.d/20-mysqli.ini,
  /etc/php/7.2/cli/conf.d/20-pdo_mysql.ini,
  /etc/php/7.2/cli/conf.d/20-phar.ini,
  /etc/php/7.2/cli/conf.d/20-posix.ini,
  /etc/php/7.2/cli/conf.d/20-readline.ini,
  /etc/php/7.2/cli/conf.d/20-shmop.ini,
  /etc/php/7.2/cli/conf.d/20-simplexml.ini,
  /etc/php/7.2/cli/conf.d/20-sockets.ini,
  /etc/php/7.2/cli/conf.d/20-sysvmsg.ini,
  /etc/php/7.2/cli/conf.d/20-sysvsem.ini,
  /etc/php/7.2/cli/conf.d/20-sysvshm.ini,
  /etc/php/7.2/cli/conf.d/20-tokenizer.ini,
  /etc/php/7.2/cli/conf.d/20-wddx.ini,
  /etc/php/7.2/cli/conf.d/20-xmlreader.ini,
  /etc/php/7.2/cli/conf.d/20-xmlrpc.ini,
  /etc/php/7.2/cli/conf.d/20-xmlwriter.ini,
  /etc/php/7.2/cli/conf.d/20-xsl.ini,
  /etc/php/7.2/cli/conf.d/20-zip.ini
  /etc/php/7.2/cli/conf.d/20-sysvmsg.ini,
  /etc/php/7.2/cli/conf.d/20-sysvsem.ini,
  /etc/php/7.2/cli/conf.d/20-sysvshm.ini,
  /etc/php/7.2/cli/conf.d/20-tokenizer.ini,
  /etc/php/7.2/cli/conf.d/20-wddx.ini,
  /etc/php/7.2/cli/conf.d/20-xmlreader.ini,
  /etc/php/7.2/cli/conf.d/20-xmlrpc.ini,
  /etc/php/7.2/cli/conf.d/20-xmlwriter.ini,
  /etc/php/7.2/cli/conf.d/20-xsl.ini,
  /etc/php/7.2/cli/conf.d/20-zip.ini

**Comment by wilmoore** [comment]
I've actually never tried it on ubuntu. I've only ever used it on macos but I'll try to help where I can:

* What's in your `/etc/php/` directory?

**Comment by daraul** [comment]
These folders:
/7.2
/7.1
/7.0
/5.6

All with the same structure:
/cli/php.ini
/cli/conf.d

7.1 and 7.2 have apache as well, but that wouldn't matter would it?

**Comment by wilmoore** [comment]
Is this still giving you trouble or have you moved on to something else?

**Comment by daraul** [comment]
I've since moved to Arch, so no :laughing:
