### ISSUE TITLE
Can not work

### ISSUE THREAD

**Issue by Birjemin** [wilmoore/php-version#70]
Hello~~~I get problem!!Can you help me??
1.php70:
![image](https://user-images.githubusercontent.com/10378934/40913903-cfd0c8d0-6828-11e8-9505-1e64cc3bf270.png)

2.php71
![image](https://user-images.githubusercontent.com/10378934/40913913-d49c8890-6828-11e8-8d27-e65ff549c924.png)

3.~/.bash_profile(in my ~/.zshrc "")
![image](https://user-images.githubusercontent.com/10378934/40913981-0ddba4b0-6829-11e8-8c2b-58d73cf4d262.png)

![image](https://user-images.githubusercontent.com/10378934/40914174-bcf3791e-6829-11e8-92eb-9fe9cc38c982.png)

4.Nothing!
![image](https://user-images.githubusercontent.com/10378934/40914046-3db20076-6829-11e8-9d19-c0561e01fe08.png)

5.bug-report
## System

  Darwin Birjemin-5.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

## Script

  TYPE:    php-version
  VERSION: php-version v0.12.0

## Environment

  SHELL:        /bin/zsh
  PATH:         /usr/local/opt/elasticsearch@5.6/bin:/usr/local/opt/openssl/bin:/usr/local/opt/elasticsearch@5.6/bin:/usr/local/opt/openssl/bin:/usr/local/opt/elasticsearch@5.6/bin:/usr/local/opt/openssl/bin:/usr/local/opt/elasticsearch@5.6/bin:/usr/local/opt/openssl/bin:/usr/local/opt/elasticsearch@5.6/bin:/usr/local/opt/openssl/bin:/usr/local/Cellar/php70/7.0.27_19/bin:/usr/local/opt/elasticsearch@5.6/bin:/usr/local/opt/openssl/bin:/usr/local/Cellar/php70/7.0.27.19/bin:/usr/local/opt/elasticsearch@5.6/bin:/usr/local/opt/openssl/bin:/usr/local/Cellar/php70/7.0.27.19/bin:/usr/local/opt/elasticsearch@5.6/bin:/usr/local/opt/openssl/bin:/usr/local/Cellar/php70/7.0.27.19/bin:/usr/local/opt/elasticsearch@5.6/bin:/usr/local/opt/openssl/bin:/usr/local/opt/elasticsearch@5.6/bin:/usr/local/opt/openssl/bin:/Users/birjemin/.nvm/versions/node/v9.0.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/birjemin/.composer/vendor/bin:GOBIN:/Library/Maven/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/birjemin/.composer/vendor/bin:GOBIN:/Library/Maven/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/birjemin/.composer/vendor/bin:GOBIN:/Library/Maven/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/birjemin/.composer/vendor/bin:GOBIN:/Library/Maven/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/birjemin/.composer/vendor/bin:GOBIN:/Library/Maven/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/birjemin/.composer/vendor/bin:GOBIN:/Library/Maven/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/birjemin/.composer/vendor/bin:GOBIN:/Library/Maven/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/birjemin/.composer/vendor/bin:GOBIN:/Library/Maven/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/birjemin/.composer/vendor/bin:GOBIN:/Library/Maven/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/birjemin/.composer/vendor/bin:GOBIN:/Library/Maven/bin
  PHPS:         
  PHP_VERSIONS: /usr/local/Cellar/php70 /usr/local/Cellar/php71

## Homebrew

  VERSION: Homebrew 1.6.6
Homebrew/homebrew-core (git revision 70def; last commit 2018-06-04)
  PATH:    /usr/local/bin/brew
  PHPS:    

## PHP

  VERSION: 7.0.27

## INI

  Configuration File (php.ini) Path: /usr/local/etc/php/7.0
  Loaded Configuration File:         /usr/local/etc/php/7.0/php.ini
  Scan for additional .ini files in: /usr/local/etc/php/7.0/conf.d
  Additional .ini files parsed:      /usr/local/etc/php/7.0/conf.d/ext-igbinary.ini,
  /usr/local/etc/php/7.0/conf.d/ext-memcached.ini,
  /usr/local/etc/php/7.0/conf.d/ext-mongodb.ini,
  /usr/local/etc/php/7.0/conf.d/ext-redis.ini,
  /usr/local/etc/php/7.0/conf.d/ext-swoole.ini,
  /usr/local/etc/php/7.0/conf.d/ext-tideways_xhprof.ini,
  /usr/local/etc/php/7.0/conf.d/ext-xdebug.ini,
  /usr/local/etc/php/7.0/conf.d/ext-xhprof.ini

**Comment by wilmoore** [comment]
Hi @Birjemin - are you still having trouble with this?

**Comment by Birjemin** [comment]
Yeah,so ...I gave up..

> Hi @Birjemin - are you still having trouble with this?

**Comment by wilmoore** [comment]
@Birjemin - fair enough. If you do happen to try again with the latest version, I will be able to respond a bit more swiftly should you encounter any issues. Thanks!
