### ISSUE TITLE
homebrew/php was deprecated

### ISSUE THREAD

**Issue by TIGERB** [wilmoore/php-version#71]
When I execute "homebrew/php was deprecated" in my mac(mac os 10.13.3 (17D47)), I got the error as follows:

```
Updating Homebrew...
Error: homebrew/php was deprecated. This tap is now empty as all its formulae were migrated.
```

**Comment by Pictor13** [comment]
https://brew.sh/2018/01/19/homebrew-1.5.0/

**Comment by TIGERB** [comment]
I cant open it

**Comment by Pictor13** [comment]
https://webcache.googleusercontent.com/search?q=cache:https%3A%2F%2Fbrew.sh%2F2018%2F01%2F19%2Fhomebrew-1.5.0%2F

**Comment by TIGERB** [comment]
yeah, got it, thx
